// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHL6bZceyKf9yQcVV6XS62TQChAQwvql8',
    appId: '1:269956440741:web:29e6b0120b53aabe8b634c',
    messagingSenderId: '269956440741',
    projectId: 'attendity-20f5b',
    authDomain: 'attendity-20f5b.firebaseapp.com',
    storageBucket: 'attendity-20f5b.appspot.com',
    measurementId: 'G-P1PHV0J8TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB-8VMrpT6J7Q1UForjHqM6SZfYj-P_bQ',
    appId: '1:269956440741:android:8aa9d121a6e1f22f8b634c',
    messagingSenderId: '269956440741',
    projectId: 'attendity-20f5b',
    storageBucket: 'attendity-20f5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB86wv4LSoZZ5OAHwOd3E_hi3V8krZ6A_s',
    appId: '1:269956440741:ios:143c2deb2b13efc28b634c',
    messagingSenderId: '269956440741',
    projectId: 'attendity-20f5b',
    storageBucket: 'attendity-20f5b.appspot.com',
    iosBundleId: 'com.example.attendity',
  );
}
